# Generated by Django 5.0.7 on 2024-08-04 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='distancerecord',
            index=models.Index(fields=['start_location', 'end_location'], name='distance_di_start_l_1b9ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='distance_lo_name_cc7b12_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='distance_lo_latitud_949305_idx'),
        ),
    ]
