# Generated by Django 5.0.7 on 2024-08-08 19:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0002_distancerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='distancerecord',
            name='distance_km',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AddIndex(
            model_name='distancerecord',
            index=models.Index(fields=['created_at'], name='distance_di_created_d1d7de_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='distance_lo_search__1ca7ea_gin'),
        ),
    ]
